//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAC_1.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PAC_1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zręczność (kontrola motoryki).
        /// </summary>
        internal static string AgilitySubcathegoryName {
            get {
                return ResourceManager.GetString("AgilitySubcathegoryName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Komunikacja.
        /// </summary>
        internal static string CommunicationCathegoryName {
            get {
                return ResourceManager.GetString("CommunicationCathegoryName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ujmowanie różnic.
        /// </summary>
        internal static string DifferentiationSubcathegoryName {
            get {
                return ResourceManager.GetString("DifferentiationSubcathegoryName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ubieranie się.
        /// </summary>
        internal static string DressingUpSubcathegoryName {
            get {
                return ResourceManager.GetString("DressingUpSubcathegoryName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czynnści domowe.
        /// </summary>
        internal static string HouseworkSubcathegoryName {
            get {
                return ResourceManager.GetString("HouseworkSubcathegoryName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Język.
        /// </summary>
        internal static string LanguageSubcathegoryName {
            get {
                return ResourceManager.GetString("LanguageSubcathegoryName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sprawność manualna (ruchy palców).
        /// </summary>
        internal static string ManualSkillsSubcathegoryName {
            get {
                return ResourceManager.GetString("ManualSkillsSubcathegoryName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sprawność motoryczna.
        /// </summary>
        internal static string MotorSkillsSubcathegoryName {
            get {
                return ResourceManager.GetString("MotorSkillsSubcathegoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] NotoSerif_Bold {
            get {
                object obj = ResourceManager.GetObject("NotoSerif_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] NotoSerif_BoldItalic {
            get {
                object obj = ResourceManager.GetObject("NotoSerif_BoldItalic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] NotoSerif_Condensed {
            get {
                object obj = ResourceManager.GetObject("NotoSerif_Condensed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] NotoSerif_CondensedBold {
            get {
                object obj = ResourceManager.GetObject("NotoSerif_CondensedBold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] NotoSerif_CondensedBoldItalic {
            get {
                object obj = ResourceManager.GetObject("NotoSerif_CondensedBoldItalic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] NotoSerif_CondensedItalic {
            get {
                object obj = ResourceManager.GetObject("NotoSerif_CondensedItalic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] NotoSerif_Light {
            get {
                object obj = ResourceManager.GetObject("NotoSerif_Light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] NotoSerif_LightItalic {
            get {
                object obj = ResourceManager.GetObject("NotoSerif_LightItalic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] NotoSerif_Regular {
            get {
                object obj = ResourceManager.GetObject("NotoSerif_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Liczby i wielkości.
        /// </summary>
        internal static string NumbersAndSizesSubcathegoryName {
            get {
                return ResourceManager.GetString("NumbersAndSizesSubcathegoryName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zajęcia.
        /// </summary>
        internal static string OccupationCathegoryName {
            get {
                return ResourceManager.GetString("OccupationCathegoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PAC1Diagram {
            get {
                object obj = ResourceManager.GetObject("PAC1Diagram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Posługiwanie się ołówkiem i papierem.
        /// </summary>
        internal static string PencilAndPaperSkillsSubcathegoryName {
            get {
                return ResourceManager.GetString("PencilAndPaperSkillsSubcathegoryName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Udział w zabawie.
        /// </summary>
        internal static string PlayingSubcathegoryName {
            get {
                return ResourceManager.GetString("PlayingSubcathegoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] Questions {
            get {
                object obj = ResourceManager.GetObject("Questions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ./Questions.json.
        /// </summary>
        internal static string QuestionsSource {
            get {
                return ResourceManager.GetString("QuestionsSource", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Obsługiwanie Siebie.
        /// </summary>
        internal static string SelfHelpCathegoryName {
            get {
                return ResourceManager.GetString("SelfHelpCathegoryName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Uspołecznienie.
        /// </summary>
        internal static string SocialisationCathegotyName {
            get {
                return ResourceManager.GetString("SocialisationCathegotyName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zachowanie przy stole.
        /// </summary>
        internal static string TableMannersSubcathegoryName {
            get {
                return ResourceManager.GetString("TableMannersSubcathegoryName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Toaleta i mycie.
        /// </summary>
        internal static string ToiletAndWashingSubcathegoryName {
            get {
                return ResourceManager.GetString("ToiletAndWashingSubcathegoryName", resourceCulture);
            }
        }
    }
}
